import SpeciesDictionary from "../models/speciesDictionary.model.js";
import sequelize from "../lib/db.js";
import dotenv from "dotenv";

dotenv.config();

const fishSpeciesData = [
    // Freshwater Species
    {
        common_name: "Neon Tetra",
        scientific_name: "Paracheirodon innesi",
        family: "Characidae",
        origin: "South America - Amazon Basin",
        description: "Small, peaceful schooling fish with striking blue and red coloration. Best kept in groups of 6 or more.",
        water_type: "freshwater",
        min_temp: 20,
        max_temp: 26,
        min_ph: 6.0,
        max_ph: 7.0,
        min_hardness: 1,
        max_hardness: 10,
        diet_type: "omnivore",
        diet_info: "Accepts flakes, micro pellets, and small live/frozen foods",
        max_size_cm: 4,
        min_tank_size_liters: 40,
        care_level: "easy",
        temperament: "peaceful",
        breeding_difficulty: "moderate",
        breeding_notes: "Egg scatterers, requires soft acidic water",
        primary_image: "https://images.unsplash.com/photo-1520990735534-c93d2e2c0b5e?w=400",
        status: "published"
    },
    {
        common_name: "Betta Fish",
        scientific_name: "Betta splendens",
        family: "Osphronemidae",
        origin: "Southeast Asia - Thailand",
        description: "Beautiful labyrinth fish known for elaborate fins and vibrant colors. Males are territorial.",
        water_type: "freshwater",
        min_temp: 24,
        max_temp: 28,
        min_ph: 6.5,
        max_ph: 7.5,
        min_hardness: 5,
        max_hardness: 15,
        diet_type: "carnivore",
        diet_info: "Prefers live/frozen foods, high-quality pellets",
        max_size_cm: 7,
        min_tank_size_liters: 20,
        care_level: "easy",
        temperament: "aggressive",
        breeding_difficulty: "easy",
        breeding_notes: "Bubble nest builder, males guard eggs",
        primary_image: "https://images.unsplash.com/photo-1520302630591-fd1c66edc19d?w=400",
        status: "published"
    },
    {
        common_name: "Angelfish",
        scientific_name: "Pterophyllum scalare",
        family: "Cichlidae",
        origin: "South America - Amazon River",
        description: "Elegant cichlid with distinctive triangular shape. Peaceful when young but can be territorial as adults.",
        water_type: "freshwater",
        min_temp: 24,
        max_temp: 28,
        min_ph: 6.0,
        max_ph: 7.5,
        min_hardness: 3,
        max_hardness: 12,
        diet_type: "omnivore",
        diet_info: "Quality flakes, pellets, and live/frozen foods",
        max_size_cm: 15,
        min_tank_size_liters: 150,
        care_level: "moderate",
        temperament: "semi_aggressive",
        breeding_difficulty: "moderate",
        breeding_notes: "Substrate spawners, parents guard eggs",
        primary_image: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=400",
        status: "published"
    },
    {
        common_name: "Guppy",
        scientific_name: "Poecilia reticulata",
        family: "Poeciliidae",
        origin: "South America - Trinidad and Tobago",
        description: "Popular livebearer with colorful males. Easy to breed and care for, perfect for beginners.",
        water_type: "freshwater",
        min_temp: 22,
        max_temp: 28,
        min_ph: 7.0,
        max_ph: 8.5,
        min_hardness: 10,
        max_hardness: 25,
        diet_type: "omnivore",
        diet_info: "Flakes, algae, small live foods",
        max_size_cm: 6,
        min_tank_size_liters: 40,
        care_level: "very_easy",
        temperament: "peaceful",
        breeding_difficulty: "very_easy",
        breeding_notes: "Livebearers, females give birth to free-swimming fry",
        primary_image: "https://images.unsplash.com/photo-1553456558-aff63285bdd1?w=400",
        status: "published"
    },
    {
        common_name: "Discus",
        scientific_name: "Symphysodon aequifasciatus",
        family: "Cichlidae",
        origin: "South America - Amazon River",
        description: "King of the aquarium, requires pristine water conditions and stable parameters. Beautiful disc-shaped body.",
        water_type: "freshwater",
        min_temp: 26,
        max_temp: 30,
        min_ph: 6.0,
        max_ph: 7.0,
        min_hardness: 1,
        max_hardness: 8,
        diet_type: "carnivore",
        diet_info: "High-protein foods, bloodworms, brine shrimp",
        max_size_cm: 20,
        min_tank_size_liters: 200,
        care_level: "expert",
        temperament: "peaceful",
        breeding_difficulty: "very_difficult",
        breeding_notes: "Parents care for young, fry feed on parental slime coat",
        primary_image: "https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=400",
        status: "published"
    },
    {
        common_name: "Cardinal Tetra",
        scientific_name: "Paracheirodon axelrodi",
        family: "Characidae",
        origin: "South America - Rio Negro",
        description: "Similar to neon tetra but with more vibrant red coloration extending the full length of the body.",
        water_type: "freshwater",
        min_temp: 23,
        max_temp: 27,
        min_ph: 5.5,
        max_ph: 7.0,
        min_hardness: 1,
        max_hardness: 8,
        diet_type: "omnivore",
        diet_info: "Small flakes, micro pellets, frozen foods",
        max_size_cm: 5,
        min_tank_size_liters: 60,
        care_level: "easy",
        temperament: "peaceful",
        breeding_difficulty: "difficult",
        breeding_notes: "Requires very soft, acidic water for breeding",
        primary_image: "https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?w=400",
        status: "published"
    },
    {
        common_name: "Corydoras Catfish",
        scientific_name: "Corydoras paleatus",
        family: "Callichthyidae",
        origin: "South America - Brazil, Argentina",
        description: "Popular bottom-dwelling catfish. Social and should be kept in groups of 6 or more.",
        water_type: "freshwater",
        min_temp: 20,
        max_temp: 26,
        min_ph: 6.5,
        max_ph: 7.5,
        min_hardness: 5,
        max_hardness: 15,
        diet_type: "omnivore",
        diet_info: "Sinking pellets, algae wafers, frozen foods",
        max_size_cm: 7,
        min_tank_size_liters: 60,
        care_level: "easy",
        temperament: "peaceful",
        breeding_difficulty: "moderate",
        breeding_notes: "T-position spawning, eggs laid on glass or plants",
        primary_image: "https://images.unsplash.com/photo-1522720833242-7b4e99f467e8?w=400",
        status: "published"
    },
    {
        common_name: "Cherry Barb",
        scientific_name: "Puntius titteya",
        family: "Cyprinidae",
        origin: "Sri Lanka",
        description: "Peaceful barb with stunning red coloration in males. Hardy and adaptable to various conditions.",
        water_type: "freshwater",
        min_temp: 23,
        max_temp: 27,
        min_ph: 6.0,
        max_ph: 7.5,
        min_hardness: 5,
        max_hardness: 15,
        diet_type: "omnivore",
        diet_info: "Flakes, small pellets, vegetable matter",
        max_size_cm: 5,
        min_tank_size_liters: 80,
        care_level: "easy",
        temperament: "peaceful",
        breeding_difficulty: "easy",
        breeding_notes: "Egg scatterers, use spawning mop or fine-leaved plants",
        primary_image: "https://images.unsplash.com/photo-1520990735534-c93d2e2c0b5e?w=400",
        status: "published"
    },
    {
        common_name: "Zebra Danio",
        scientific_name: "Danio rerio",
        family: "Cyprinidae",
        origin: "India",
        description: "Active schooling fish with distinctive horizontal stripes. Very hardy and excellent for beginners.",
        water_type: "freshwater",
        min_temp: 18,
        max_temp: 24,
        min_ph: 6.5,
        max_ph: 8.0,
        min_hardness: 5,
        max_hardness: 20,
        diet_type: "omnivore",
        diet_info: "Flakes, small pellets, live foods",
        max_size_cm: 5,
        min_tank_size_liters: 40,
        care_level: "very_easy",
        temperament: "peaceful",
        breeding_difficulty: "easy",
        breeding_notes: "Egg scatterers, prolific breeders",
        primary_image: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=400",
        status: "published"
    },
    {
        common_name: "Pearl Gourami",
        scientific_name: "Trichopodus leerii",
        family: "Osphronemidae",
        origin: "Southeast Asia - Malaysia, Thailand",
        description: "Beautiful labyrinth fish with pearl-like spots. Males develop orange coloration when breeding.",
        water_type: "freshwater",
        min_temp: 24,
        max_temp: 28,
        min_ph: 6.0,
        max_ph: 7.5,
        min_hardness: 5,
        max_hardness: 15,
        diet_type: "omnivore",
        diet_info: "Flakes, pellets, frozen and live foods",
        max_size_cm: 12,
        min_tank_size_liters: 120,
        care_level: "easy",
        temperament: "peaceful",
        breeding_difficulty: "moderate",
        breeding_notes: "Bubble nest builders, males care for eggs",
        primary_image: "https://images.unsplash.com/photo-1553456558-aff63285bdd1?w=400",
        status: "published"
    },

    // Marine Species
    {
        common_name: "Clownfish",
        scientific_name: "Amphiprion ocellaris",
        family: "Pomacentridae",
        origin: "Indo-Pacific - Great Barrier Reef",
        description: "Popular marine fish made famous by 'Finding Nemo'. Forms symbiotic relationship with anemones.",
        water_type: "marine",
        min_temp: 24,
        max_temp: 27,
        min_ph: 8.1,
        max_ph: 8.4,
        diet_type: "omnivore",
        diet_info: "Marine flakes, pellets, frozen mysis shrimp",
        max_size_cm: 11,
        min_tank_size_liters: 100,
        care_level: "easy",
        temperament: "semi_aggressive",
        breeding_difficulty: "moderate",
        breeding_notes: "Pairs spawn regularly, eggs guarded by parents",
        primary_image: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400",
        status: "published"
    },
    {
        common_name: "Blue Tang",
        scientific_name: "Paracanthurus hepatus",
        family: "Acanthuridae",
        origin: "Indo-Pacific",
        description: "Vibrant blue surgeonfish with distinctive yellow tail. Popular but requires large swimming space.",
        water_type: "marine",
        min_temp: 24,
        max_temp: 28,
        min_ph: 8.1,
        max_ph: 8.4,
        diet_type: "herbivore",
        diet_info: "Marine algae, seaweed sheets, spirulina",
        max_size_cm: 30,
        min_tank_size_liters: 400,
        care_level: "moderate",
        temperament: "peaceful",
        breeding_difficulty: "very_difficult",
        breeding_notes: "Not successfully bred in captivity",
        primary_image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400",
        status: "published"
    },
    {
        common_name: "Royal Gramma",
        scientific_name: "Gramma loreto",
        family: "Grammatidae",
        origin: "Caribbean",
        description: "Stunning bi-colored basslet with purple front and yellow rear. Peaceful and reef-safe.",
        water_type: "marine",
        min_temp: 24,
        max_temp: 27,
        min_ph: 8.1,
        max_ph: 8.4,
        diet_type: "carnivore",
        diet_info: "Frozen mysis, brine shrimp, quality pellets",
        max_size_cm: 8,
        min_tank_size_liters: 100,
        care_level: "easy",
        temperament: "peaceful",
        breeding_difficulty: "difficult",
        breeding_notes: "Cave spawners, males guard eggs",
        primary_image: "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400",
        status: "published"
    },
    {
        common_name: "Yellow Tang",
        scientific_name: "Zebrasoma flavescens",
        family: "Acanthuridae",
        origin: "Hawaii",
        description: "Bright yellow surgeonfish, one of the most popular marine aquarium fish. Grazes on algae constantly.",
        water_type: "marine",
        min_temp: 24,
        max_temp: 28,
        min_ph: 8.1,
        max_ph: 8.4,
        diet_type: "herbivore",
        diet_info: "Nori sheets, marine algae, spirulina pellets",
        max_size_cm: 20,
        min_tank_size_liters: 300,
        care_level: "moderate",
        temperament: "semi_aggressive",
        breeding_difficulty: "very_difficult",
        breeding_notes: "Spawning observed in wild but not captive bred",
        primary_image: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=400",
        status: "published"
    },
    {
        common_name: "Mandarin Fish",
        scientific_name: "Synchiropus splendidus",
        family: "Callionymidae",
        origin: "Pacific Ocean",
        description: "Incredibly colorful dragonet with psychedelic pattern. Requires mature tank with copepods.",
        water_type: "marine",
        min_temp: 24,
        max_temp: 27,
        min_ph: 8.1,
        max_ph: 8.4,
        diet_type: "carnivore",
        diet_info: "Live copepods, amphipods, enriched brine shrimp",
        max_size_cm: 8,
        min_tank_size_liters: 150,
        care_level: "expert",
        temperament: "peaceful",
        breeding_difficulty: "difficult",
        breeding_notes: "Pair spawns at dusk, eggs released into water column",
        primary_image: "https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=400",
        status: "published"
    },
    {
        common_name: "Flame Angelfish",
        scientific_name: "Centropyge loricula",
        family: "Pomacanthidae",
        origin: "Pacific Ocean",
        description: "Stunning dwarf angelfish with brilliant red-orange coloration. Semi-aggressive but reef compatible.",
        water_type: "marine",
        min_temp: 24,
        max_temp: 27,
        min_ph: 8.1,
        max_ph: 8.4,
        diet_type: "omnivore",
        diet_info: "Marine algae, spirulina, mysis shrimp, quality pellets",
        max_size_cm: 10,
        min_tank_size_liters: 200,
        care_level: "moderate",
        temperament: "semi_aggressive",
        breeding_difficulty: "very_difficult",
        breeding_notes: "Haremic spawners, not commonly bred in captivity",
        primary_image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400",
        status: "published"
    },
    {
        common_name: "Firefish Goby",
        scientific_name: "Nemateleotris magnifica",
        family: "Microdesmidae",
        origin: "Indo-Pacific",
        description: "Graceful dartfish with elongated dorsal fin. Shy but beautiful, needs plenty of hiding spots.",
        water_type: "marine",
        min_temp: 24,
        max_temp: 27,
        min_ph: 8.1,
        max_ph: 8.4,
        diet_type: "carnivore",
        diet_info: "Frozen mysis, brine shrimp, copepods",
        max_size_cm: 9,
        min_tank_size_liters: 80,
        care_level: "easy",
        temperament: "peaceful",
        breeding_difficulty: "difficult",
        breeding_notes: "Pairs bond for life, spawning observed but challenging",
        primary_image: "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400",
        status: "published"
    },
    {
        common_name: "Six Line Wrasse",
        scientific_name: "Pseudocheilinus hexataenia",
        family: "Labridae",
        origin: "Red Sea, Indo-Pacific",
        description: "Hardy wrasse with distinctive horizontal stripes. Excellent for pest control.",
        water_type: "marine",
        min_temp: 24,
        max_temp: 27,
        min_ph: 8.1,
        max_ph: 8.4,
        diet_type: "carnivore",
        diet_info: "Frozen foods, pellets, eats bristle worms and flatworms",
        max_size_cm: 7,
        min_tank_size_liters: 120,
        care_level: "easy",
        temperament: "semi_aggressive",
        breeding_difficulty: "very_difficult",
        breeding_notes: "Protogynous hermaphrodites, challenging to breed",
        primary_image: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400",
        status: "published"
    },
    {
        common_name: "Ocellaris Clownfish",
        scientific_name: "Amphiprion ocellaris",
        family: "Pomacentridae",
        origin: "Indo-Pacific",
        description: "False clownfish, often confused with true percula clownfish. Hardy and easy to breed.",
        water_type: "marine",
        min_temp: 24,
        max_temp: 27,
        min_ph: 8.1,
        max_ph: 8.4,
        diet_type: "omnivore",
        diet_info: "Quality pellets, frozen foods, nori",
        max_size_cm: 11,
        min_tank_size_liters: 100,
        care_level: "easy",
        temperament: "semi_aggressive",
        breeding_difficulty: "easy",
        breeding_notes: "Sequential hermaphrodites, spawn every 2 weeks",
        primary_image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400",
        status: "published"
    },
    {
        common_name: "Banggai Cardinalfish",
        scientific_name: "Pterapogon kauderni",
        family: "Apogonidae",
        origin: "Banggai Islands, Indonesia",
        description: "Endangered species with striking black and white pattern. Males are mouthbrooders.",
        water_type: "marine",
        min_temp: 24,
        max_temp: 27,
        min_ph: 8.1,
        max_ph: 8.4,
        diet_type: "carnivore",
        diet_info: "Frozen mysis, brine shrimp, pellets",
        max_size_cm: 8,
        min_tank_size_liters: 100,
        care_level: "easy",
        temperament: "peaceful",
        breeding_difficulty: "moderate",
        breeding_notes: "Males carry eggs in mouth for 3-4 weeks",
        primary_image: "https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=400",
        status: "published"
    },

    // More Freshwater Species
    {
        common_name: "Molly",
        scientific_name: "Poecilia sphenops",
        family: "Poeciliidae",
        origin: "Central America",
        description: "Hardy livebearer available in many color varieties. Peaceful and easy to breed.",
        water_type: "freshwater",
        min_temp: 22,
        max_temp: 28,
        min_ph: 7.0,
        max_ph: 8.5,
        min_hardness: 10,
        max_hardness: 25,
        diet_type: "omnivore",
        diet_info: "Flakes, algae, vegetable matter",
        max_size_cm: 12,
        min_tank_size_liters: 80,
        care_level: "very_easy",
        temperament: "peaceful",
        breeding_difficulty: "very_easy",
        breeding_notes: "Livebearers, females store sperm for multiple batches",
        primary_image: "https://images.unsplash.com/photo-1553456558-aff63285bdd1?w=400",
        status: "published"
    },
    {
        common_name: "Platy",
        scientific_name: "Xiphophorus maculatus",
        family: "Poeciliidae",
        origin: "Central America - Mexico",
        description: "Colorful and peaceful livebearer. Available in many varieties including wagtail and sunset.",
        water_type: "freshwater",
        min_temp: 20,
        max_temp: 26,
        min_ph: 7.0,
        max_ph: 8.2,
        min_hardness: 10,
        max_hardness: 28,
        diet_type: "omnivore",
        diet_info: "Flakes, spirulina, vegetables",
        max_size_cm: 6,
        min_tank_size_liters: 40,
        care_level: "very_easy",
        temperament: "peaceful",
        breeding_difficulty: "very_easy",
        breeding_notes: "Prolific breeders, give birth to live fry",
        primary_image: "https://images.unsplash.com/photo-1520990735534-c93d2e2c0b5e?w=400",
        status: "published"
    },
    {
        common_name: "Swordtail",
        scientific_name: "Xiphophorus hellerii",
        family: "Poeciliidae",
        origin: "Central America",
        description: "Active livebearer with sword-like tail extension on males. Hardy and colorful.",
        water_type: "freshwater",
        min_temp: 22,
        max_temp: 28,
        min_ph: 7.0,
        max_ph: 8.3,
        min_hardness: 12,
        max_hardness: 30,
        diet_type: "omnivore",
        diet_info: "Quality flakes, algae, vegetables",
        max_size_cm: 14,
        min_tank_size_liters: 80,
        care_level: "easy",
        temperament: "peaceful",
        breeding_difficulty: "very_easy",
        breeding_notes: "Males can become aggressive when breeding",
        primary_image: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=400",
        status: "published"
    },
    {
        common_name: "Koi",
        scientific_name: "Cyprinus carpio",
        family: "Cyprinidae",
        origin: "Japan (domesticated)",
        description: "Ornamental carp breed in various colors. Requires large pond or very large aquarium.",
        water_type: "freshwater",
        min_temp: 15,
        max_temp: 25,
        min_ph: 7.0,
        max_ph: 8.5,
        min_hardness: 8,
        max_hardness: 20,
        diet_type: "omnivore",
        diet_info: "Koi pellets, vegetables, insects",
        max_size_cm: 90,
        min_tank_size_liters: 1000,
        care_level: "moderate",
        temperament: "peaceful",
        breeding_difficulty: "moderate",
        breeding_notes: "Spawning triggered by temperature changes",
        primary_image: "https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=400",
        status: "published"
    },
    {
        common_name: "Goldfish",
        scientific_name: "Carassius auratus",
        family: "Cyprinidae",
        origin: "China (domesticated)",
        description: "Classic pet fish available in many varieties. Needs cool water and large space.",
        water_type: "freshwater",
        min_temp: 18,
        max_temp: 23,
        min_ph: 7.0,
        max_ph: 8.0,
        min_hardness: 5,
        max_hardness: 19,
        diet_type: "omnivore",
        diet_info: "Goldfish pellets, vegetables, live foods",
        max_size_cm: 30,
        min_tank_size_liters: 150,
        care_level: "easy",
        temperament: "peaceful",
        breeding_difficulty: "easy",
        breeding_notes: "Egg scatterers, spawning in spring",
        primary_image: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400",
        status: "published"
    },
    {
        common_name: "Rainbowfish",
        scientific_name: "Melanotaenia boesemani",
        family: "Melanotaeniidae",
        origin: "Indonesia - New Guinea",
        description: "Stunning fish with blue front and orange rear. Active schooling fish needing groups.",
        water_type: "freshwater",
        min_temp: 24,
        max_temp: 28,
        min_ph: 7.0,
        max_ph: 8.0,
        min_hardness: 8,
        max_hardness: 20,
        diet_type: "omnivore",
        diet_info: "Quality flakes, frozen foods, vegetables",
        max_size_cm: 10,
        min_tank_size_liters: 150,
        care_level: "moderate",
        temperament: "peaceful",
        breeding_difficulty: "moderate",
        breeding_notes: "Continuous spawners, use spawning mops",
        primary_image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400",
        status: "published"
    },
    {
        common_name: "Ram Cichlid",
        scientific_name: "Mikrogeophagus ramirezi",
        family: "Cichlidae",
        origin: "South America - Venezuela, Colombia",
        description: "Dwarf cichlid with stunning coloration. Peaceful for a cichlid but needs warm water.",
        water_type: "freshwater",
        min_temp: 26,
        max_temp: 30,
        min_ph: 6.0,
        max_ph: 7.5,
        min_hardness: 5,
        max_hardness: 15,
        diet_type: "omnivore",
        diet_info: "Quality pellets, frozen foods, live foods",
        max_size_cm: 7,
        min_tank_size_liters: 80,
        care_level: "moderate",
        temperament: "peaceful",
        breeding_difficulty: "moderate",
        breeding_notes: "Substrate spawners, both parents care for fry",
        primary_image: "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400",
        status: "published"
    },
    {
        common_name: "Oscar",
        scientific_name: "Astronotus ocellatus",
        family: "Cichlidae",
        origin: "South America - Amazon",
        description: "Large, intelligent cichlid with personality. Can recognize owners and beg for food.",
        water_type: "freshwater",
        min_temp: 23,
        max_temp: 27,
        min_ph: 6.5,
        max_ph: 7.5,
        min_hardness: 5,
        max_hardness: 20,
        diet_type: "carnivore",
        diet_info: "Cichlid pellets, earthworms, small fish",
        max_size_cm: 35,
        min_tank_size_liters: 400,
        care_level: "moderate",
        temperament: "aggressive",
        breeding_difficulty: "moderate",
        breeding_notes: "Pairs bond, flat surface spawners",
        primary_image: "https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=400",
        status: "published"
    },
    {
        common_name: "Tiger Barb",
        scientific_name: "Puntigrus tetrazona",
        family: "Cyprinidae",
        origin: "Indonesia - Sumatra, Borneo",
        description: "Active schooling fish with distinctive tiger stripes. Can be fin nippers if not in large groups.",
        water_type: "freshwater",
        min_temp: 23,
        max_temp: 27,
        min_ph: 6.5,
        max_ph: 7.5,
        min_hardness: 5,
        max_hardness: 19,
        diet_type: "omnivore",
        diet_info: "Flakes, pellets, live/frozen foods",
        max_size_cm: 7,
        min_tank_size_liters: 80,
        care_level: "easy",
        temperament: "semi_aggressive",
        breeding_difficulty: "easy",
        breeding_notes: "Egg scatterers, spawning in groups",
        primary_image: "https://images.unsplash.com/photo-1520990735534-c93d2e2c0b5e?w=400",
        status: "published"
    },
    {
        common_name: "Harlequin Rasbora",
        scientific_name: "Trigonostigma heteromorpha",
        family: "Cyprinidae",
        origin: "Southeast Asia - Malaysia, Thailand",
        description: "Peaceful schooling fish with distinctive black triangular marking. Very popular community fish.",
        water_type: "freshwater",
        min_temp: 23,
        max_temp: 27,
        min_ph: 6.0,
        max_ph: 7.5,
        min_hardness: 2,
        max_hardness: 15,
        diet_type: "omnivore",
        diet_info: "Small flakes, micro pellets, live foods",
        max_size_cm: 5,
        min_tank_size_liters: 40,
        care_level: "easy",
        temperament: "peaceful",
        breeding_difficulty: "moderate",
        breeding_notes: "Eggs laid on underside of broad leaves",
        primary_image: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=400",
        status: "published"
    },
    {
        common_name: "Killifish",
        scientific_name: "Aphyosemion australe",
        family: "Nothobranchiidae",
        origin: "West Africa",
        description: "Colorful small fish with lyretail. Many species, some annual with interesting life cycle.",
        water_type: "freshwater",
        min_temp: 20,
        max_temp: 24,
        min_ph: 6.0,
        max_ph: 7.0,
        min_hardness: 2,
        max_hardness: 10,
        diet_type: "carnivore",
        diet_info: "Live foods preferred, frozen foods accepted",
        max_size_cm: 6,
        min_tank_size_liters: 40,
        care_level: "moderate",
        temperament: "peaceful",
        breeding_difficulty: "moderate",
        breeding_notes: "Plant spawners or mop spawners depending on species",
        primary_image: "https://images.unsplash.com/photo-1553456558-aff63285bdd1?w=400",
        status: "published"
    },

    // Brackish Species
    {
        common_name: "Molly (Sailfin)",
        scientific_name: "Poecilia velifera",
        family: "Poeciliidae",
        origin: "Mexico",
        description: "Large molly with impressive dorsal fin. Adaptable to fresh or brackish water.",
        water_type: "brackish",
        min_temp: 24,
        max_temp: 28,
        min_ph: 7.5,
        max_ph: 8.5,
        min_hardness: 15,
        max_hardness: 30,
        diet_type: "omnivore",
        diet_info: "Algae wafers, flakes, vegetables",
        max_size_cm: 15,
        min_tank_size_liters: 150,
        care_level: "easy",
        temperament: "peaceful",
        breeding_difficulty: "easy",
        breeding_notes: "Livebearers, breed readily in aquarium",
        primary_image: "https://images.unsplash.com/photo-1520990735534-c93d2e2c0b5e?w=400",
        status: "published"
    },
    {
        common_name: "Figure 8 Puffer",
        scientific_name: "Tetraodon biocellatus",
        family: "Tetraodontidae",
        origin: "Southeast Asia",
        description: "Small puffer with distinctive figure-8 pattern. Needs hard foods to wear down teeth.",
        water_type: "brackish",
        min_temp: 24,
        max_temp: 28,
        min_ph: 7.5,
        max_ph: 8.2,
        diet_type: "carnivore",
        diet_info: "Snails, shrimp, crunchy foods for dental health",
        max_size_cm: 8,
        min_tank_size_liters: 100,
        care_level: "moderate",
        temperament: "aggressive",
        breeding_difficulty: "very_difficult",
        breeding_notes: "Rarely bred in captivity",
        primary_image: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=400",
        status: "published"
    },
    {
        common_name: "Bumblebee Goby",
        scientific_name: "Brachygobius xanthozona",
        family: "Gobiidae",
        origin: "Southeast Asia",
        description: "Small goby with yellow and black bands. Prefers brackish water but tolerates fresh.",
        water_type: "brackish",
        min_temp: 24,
        max_temp: 28,
        min_ph: 7.5,
        max_ph: 8.5,
        diet_type: "carnivore",
        diet_info: "Live/frozen foods preferred, may accept pellets",
        max_size_cm: 4,
        min_tank_size_liters: 40,
        care_level: "moderate",
        temperament: "peaceful",
        breeding_difficulty: "difficult",
        breeding_notes: "Cave spawners, males guard eggs",
        primary_image: "https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=400",
        status: "published"
    },
    {
        common_name: "Archer Fish",
        scientific_name: "Toxotes jaculatrix",
        family: "Toxotidae",
        origin: "Southeast Asia, Australia",
        description: "Famous for shooting water to knock down insects. Needs large tank with low water level.",
        water_type: "brackish",
        min_temp: 25,
        max_temp: 28,
        min_ph: 7.0,
        max_ph: 8.0,
        diet_type: "carnivore",
        diet_info: "Insects, crickets, frozen foods",
        max_size_cm: 30,
        min_tank_size_liters: 300,
        care_level: "moderate",
        temperament: "semi_aggressive",
        breeding_difficulty: "very_difficult",
        breeding_notes: "Not bred in home aquariums",
        primary_image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400",
        status: "published"
    },
    {
        common_name: "Mudskipper",
        scientific_name: "Periophthalmus barbarus",
        family: "Oxudercidae",
        origin: "Africa, Asia",
        description: "Amphibious fish that spends time on land. Requires specialized paludarium setup.",
        water_type: "brackish",
        min_temp: 25,
        max_temp: 30,
        min_ph: 7.5,
        max_ph: 8.5,
        diet_type: "carnivore",
        diet_info: "Live insects, frozen foods, pellets",
        max_size_cm: 15,
        min_tank_size_liters: 150,
        care_level: "expert",
        temperament: "territorial",
        breeding_difficulty: "very_difficult",
        breeding_notes: "Burrow spawners, requires mud substrate",
        primary_image: "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400",
        status: "published"
    },
    {
        common_name: "Knight Goby",
        scientific_name: "Stigmatogobius sadanundio",
        family: "Gobiidae",
        origin: "Asia",
        description: "Peaceful bottom-dwelling goby. Good for brackish community tanks.",
        water_type: "brackish",
        min_temp: 20,
        max_temp: 26,
        min_ph: 7.0,
        max_ph: 8.5,
        diet_type: "carnivore",
        diet_info: "Sinking pellets, frozen bloodworms, brine shrimp",
        max_size_cm: 9,
        min_tank_size_liters: 80,
        care_level: "easy",
        temperament: "peaceful",
        breeding_difficulty: "moderate",
        breeding_notes: "Cave spawners in brackish conditions",
        primary_image: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400",
        status: "published"
    },

    // Additional Freshwater
    {
        common_name: "African Cichlid",
        scientific_name: "Pseudotropheus zebra",
        family: "Cichlidae",
        origin: "Lake Malawi, Africa",
        description: "Colorful and active cichlid from African rift lakes. Requires hard, alkaline water.",
        water_type: "freshwater",
        min_temp: 23,
        max_temp: 28,
        min_ph: 7.5,
        max_ph: 8.5,
        min_hardness: 10,
        max_hardness: 25,
        diet_type: "omnivore",
        diet_info: "Spirulina flakes, cichlid pellets, vegetables",
        max_size_cm: 15,
        min_tank_size_liters: 200,
        care_level: "moderate",
        temperament: "aggressive",
        breeding_difficulty: "easy",
        breeding_notes: "Mouthbrooders, females incubate eggs in mouth",
        primary_image: "https://images.unsplash.com/photo-1520990735534-c93d2e2c0b5e?w=400",
        status: "published"
    },
    {
        common_name: "Glass Catfish",
        scientific_name: "Kryptopterus vitreolus",
        family: "Siluridae",
        origin: "Southeast Asia - Thailand",
        description: "Transparent catfish that schools in mid-water. Unique and peaceful.",
        water_type: "freshwater",
        min_temp: 24,
        max_temp: 26,
        min_ph: 6.5,
        max_ph: 7.5,
        min_hardness: 5,
        max_hardness: 19,
        diet_type: "omnivore",
        diet_info: "Small live foods, frozen foods, flakes",
        max_size_cm: 12,
        min_tank_size_liters: 100,
        care_level: "moderate",
        temperament: "peaceful",
        breeding_difficulty: "very_difficult",
        breeding_notes: "Breeding not commonly achieved in home aquariums",
        primary_image: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=400",
        status: "published"
    },
    {
        common_name: "Black Ghost Knifefish",
        scientific_name: "Apteronotus albifrons",
        family: "Apteronotidae",
        origin: "South America",
        description: "Nocturnal electric fish with undulating movement. Needs caves and dim lighting.",
        water_type: "freshwater",
        min_temp: 23,
        max_temp: 28,
        min_ph: 6.0,
        max_ph: 7.5,
        min_hardness: 5,
        max_hardness: 19,
        diet_type: "carnivore",
        diet_info: "Live/frozen bloodworms, brine shrimp, tubifex",
        max_size_cm: 50,
        min_tank_size_liters: 400,
        care_level: "expert",
        temperament: "semi_aggressive",
        breeding_difficulty: "very_difficult",
        breeding_notes: "Not bred in home aquariums",
        primary_image: "https://images.unsplash.com/photo-1553456558-aff63285bdd1?w=400",
        status: "published"
    },
    {
        common_name: "Celestial Pearl Danio",
        scientific_name: "Danio margaritatus",
        family: "Cyprinidae",
        origin: "Myanmar",
        description: "Tiny, stunning danio discovered in 2006. Blue body with pearl-like spots.",
        water_type: "freshwater",
        min_temp: 20,
        max_temp: 24,
        min_ph: 6.5,
        max_ph: 7.5,
        min_hardness: 2,
        max_hardness: 10,
        diet_type: "omnivore",
        diet_info: "Micro foods, baby brine shrimp, crushed flakes",
        max_size_cm: 3,
        min_tank_size_liters: 40,
        care_level: "moderate",
        temperament: "peaceful",
        breeding_difficulty: "easy",
        breeding_notes: "Continuous spawners with dense plant cover",
        primary_image: "https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=400",
        status: "published"
    },
    {
        common_name: "Endler's Livebearer",
        scientific_name: "Poecilia wingei",
        family: "Poeciliidae",
        origin: "Venezuela",
        description: "Small, colorful relative of guppies. Males have stunning metallic colors.",
        water_type: "freshwater",
        min_temp: 24,
        max_temp: 30,
        min_ph: 7.0,
        max_ph: 8.5,
        min_hardness: 15,
        max_hardness: 30,
        diet_type: "omnivore",
        diet_info: "Micro flakes, algae, baby brine shrimp",
        max_size_cm: 4,
        min_tank_size_liters: 40,
        care_level: "very_easy",
        temperament: "peaceful",
        breeding_difficulty: "very_easy",
        breeding_notes: "Livebearers, breed constantly",
        primary_image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400",
        status: "published"
    }
];

async function seedSpecies() {
    try {
        // Connect to database
        // await sequelize.authenticate();
        // console.log("✅ Connected to database");

        // Sync models (creates tables if they don't exist)
        // await sequelize.sync();
        // console.log("✅ Models synced");

        // Check if species already exist
        const existingCount = await SpeciesDictionary.count();
        console.log(`📊 Existing species count: ${existingCount}`);

        // Insert species data
        console.log(`🌱 Seeding ${fishSpeciesData.length} species...`);

        let successCount = 0;
        let skipCount = 0;

        for (const species of fishSpeciesData) {
            try {
                // Check for duplicates
                const existing = await SpeciesDictionary.findOne({
                    where: {
                        common_name: species.common_name,
                        scientific_name: species.scientific_name
                    }
                });

                if (existing) {
                    console.log(`⏭️  Skipping: ${species.common_name} (already exists)`);
                    skipCount++;
                    continue;
                }

                await SpeciesDictionary.create(species);
                console.log(`✅ Added: ${species.common_name}`);
                successCount++;

                setTimeout(() => {}, 1000); // Slight delay to avoid overwhelming the DB
            } catch (error) {
                console.error(`❌ Error adding ${species.common_name}:`, error.message);
            }
        }

        console.log("\n📊 Seeding Summary:");
        console.log(`   ✅ Successfully added: ${successCount} species`);
        console.log(`   ⏭️  Skipped (duplicates): ${skipCount} species`);
        console.log(`   📈 Total in database: ${await SpeciesDictionary.count()} species`);

        process.exit(0);
    } catch (error) {
        console.error("❌ Seeding failed:", error);
        process.exit(1);
    }
}

// Run the seed function
seedSpecies();